steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/boxing-gym-agent:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/boxing-gym-agent:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'boxing-gym-agent'
    - '--image'
    - 'gcr.io/$PROJECT_ID/boxing-gym-agent:latest'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--timeout'
    - '3600'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID},GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET},GMAIL_USER_EMAIL=${_GMAIL_USER_EMAIL},BOXING_GYM_EMAIL=${_BOXING_GYM_EMAIL},BOXING_GYM_NAME=${_BOXING_GYM_NAME},LLM_PROVIDER=${_LLM_PROVIDER},OPENAI_API_KEY=${_OPENAI_API_KEY},ANTHROPIC_API_KEY=${_ANTHROPIC_API_KEY},LLM_MODEL=${_LLM_MODEL},CHECK_INTERVAL_MINUTES=${_CHECK_INTERVAL_MINUTES},CONFIDENCE_THRESHOLD=${_CONFIDENCE_THRESHOLD},ENABLE_CALENDAR_CREATION=${_ENABLE_CALENDAR_CREATION}'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/boxing-gym-agent:latest'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

# Substitution variables (set these in Cloud Build triggers)
substitutions:
  _GOOGLE_CLIENT_ID: 'your_google_client_id'
  _GOOGLE_CLIENT_SECRET: 'your_google_client_secret'
  _GMAIL_USER_EMAIL: 'your_email@gmail.com'
  _BOXING_GYM_EMAIL: 'your_boxing_gym@gmail.com'
  _BOXING_GYM_NAME: 'Your Boxing Gym'
  _LLM_PROVIDER: 'openai'
  _OPENAI_API_KEY: 'your_openai_api_key'
  _ANTHROPIC_API_KEY: 'your_anthropic_api_key'
  _LLM_MODEL: 'gpt-4-turbo-preview'
  _CHECK_INTERVAL_MINUTES: '5'
  _CONFIDENCE_THRESHOLD: '0.7'
  _ENABLE_CALENDAR_CREATION: 'true'
